### ISSUE TITLE
how to use this project to train self model .?

### ISSUE THREAD

**Issue by ThinkInFuture** [Irisfee/spotify_analysis#1]

**Comment by Irisfee** [comment]
You can follow the link in the project description.

**Comment by ThinkInFuture** [comment]
these is no train scripts release right ?



---Original---
From: "Yufei ***@***.***&gt;
Date: Mon, Jan 16, 2023 11:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Irisfee/spotify_analysis] how to use this project to train selfmodel .? (Issue #1)




 
Closed #1 as completed.
